Fix on_error triggered twice issue
demsking/image-downloader pull request #5
Opened 2017-01-17 08:51 UTC by jiji262

If some error happens, the on_error will be triggered twice.

2017-01-17 19:41 UTC, demsking requested changes

2017-01-17 19:41 UTC, demsking commented on index.js
> +            return;
Thanks for your contribution :-)

Could you use a one line return statement please ?
`return on_error(err, options);`

2017-01-18 01:26 UTC, jiji262 commented
done.

2017-01-18 12:14 UTC, demsking approved these changes

2017-01-18 12:16 UTC, merged